In [1]:
import pandas as pd

file_path = "../data_raw/UrbanScape Apparel SEO Performance Final Dataset.xlsx"

df = pd.read_excel(file_path)

print("Shape:", df.shape)

df.head()

Shape: (9996, 44)

,Date,Month,Year,Quarter,Time Of Day,Primary Keywords,Secondary Keywords,Long-Tail Keywords,Location,Social Media Source,...,Organic_Revenue ($),Page_Load_Time (sec),Core_Web_Vitals_LCP (sec),Core_Web_Vitals_FID (ms),Core_Web_Vitals_CLS,Social_Shares,Referral_Traffic,Technical_SEO_Errors,Bounce_Rate_by_Device_Mobile (%),Time_to_First_Byte_TTFB (ms)
0,2023-01-01 00:00:00,January,2023,Q1,Night,eco-friendly accessories,eco-friendly hiking gear,eco-friendly clothing for hikers,Mexico,Pinterest,...,3597.90,2.87,2.70,448.84,0.30,247,2937,13,51.94,453
1,2023-01-01 01:00:00,January,2023,Q1,Night,eco-friendly accessories,eco-friendly hiking gear,biodegradable outdoor clothing,Mexico,Twitter,...,5806.19,4.42,4.31,839.17,0.18,414,1909,19,56.62,437
2,2023-01-01 02:00:00,January,2023,Q1,Night,vegan leather handbags,sustainable activewear,sustainable fashion for athletes,Australia,Instagram,...,1170.33,9.48,3.93,388.88,0.57,373,3059,7,49.62,1077
3,2023-01-01 03:00:00,January,2023,Q1,Night,organic cotton apparel,eco-friendly sportswear,where to buy recycled polyester running shorts,Mexico,TikTok,...,1182.17,4.90,1.51,840.83,0.22,134,3264,7,50.74,1202
4,2023-01-01 04:00:00,January,2023,Q1,Night,organic cotton apparel,sustainable activewear,eco-friendly clothing for hikers,Germany,YouTube,...,692.14,1.89,3.49,524.28,0.26,24,1631,14,67.05,313

In [2]:
df.columns

Index(['Date', 'Month', 'Year', 'Quarter', 'Time Of Day', 'Primary Keywords',
       'Secondary Keywords', 'Long-Tail Keywords', 'Location',
       'Social Media Source', 'Media Type', 'Device Type', 'Organic_Traffic',
       'Keywords_Ranking', 'Clicks', 'Impressions', 'CTR (%)',
       'Average_Position', 'Backlinks', 'Domain_Authority', 'Bounce_Rate (%)',
       'Pages_per_Session', 'Organic_vs_Paid_Traffic_Split (%)',
       'Organic_Traffic_Growth_Rate (%)', 'Conversion_Rate (%)',
       'Goal_Completions', 'Average_Session_Duration (sec)',
       'New_vs_Returning_Visitors (%)', 'Exit_Rate (%)', 'Top_Landing_Pages',
       'Keyword_Difficulty', 'CPC_for_Paid_Keywords ($)', 'Indexed_Pages',
       'Mobile_vs_Desktop_Traffic_Split (%)', 'Organic_Revenue ($)',
       'Page_Load_Time (sec)', 'Core_Web_Vitals_LCP (sec)',
       'Core_Web_Vitals_FID (ms)', 'Core_Web_Vitals_CLS', 'Social_Shares',
       'Referral_Traffic', 'Technical_SEO_Errors',
       'Bounce_Rate_by_Device_Mobile (%)', 'Time_to_First_Byte_TTFB (ms)'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 44 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Date                                 9996 non-null   datetime64[us]
 1   Month                                9996 non-null   str
 2   Year                                 9996 non-null   int64
 3   Quarter                              9996 non-null   str
 4   Time Of Day                          9996 non-null   str
 5   Primary Keywords                     9996 non-null   str
 6   Secondary Keywords                   9996 non-null   str
 7   Long-Tail Keywords                   9996 non-null   str
 8   Location                             9996 non-null   str
 9   Social Media Source                  9996 non-null   str
 10  Media Type                           9996 non-null   str
 11  Device Type                          9996 non-null   str
 12  Organic_Traffic                      9996 non-null   int64
 13  Keywords_Ranking                     9996 non-null   int64
 14  Clicks                               9996 non-null   int64
 15  Impressions                          9996 non-null   int64
 16  CTR (%)                              9996 non-null   float64
 17  Average_Position                     9996 non-null   float64
 18  Backlinks                            9996 non-null   int64
 19  Domain_Authority                     9996 non-null   int64
 20  Bounce_Rate (%)                      9996 non-null   float64
 21  Pages_per_Session                    9996 non-null   float64
 22  Organic_vs_Paid_Traffic_Split (%)    9996 non-null   float64
 23  Organic_Traffic_Growth_Rate (%)      9996 non-null   float64
 24  Conversion_Rate (%)                  9996 non-null   float64
 25  Goal_Completions                     9996 non-null   int64
 26  Average_Session_Duration (sec)       9996 non-null   int64
 27  New_vs_Returning_Visitors (%)        9996 non-null   float64
 28  Exit_Rate (%)                        9996 non-null   float64
 29  Top_Landing_Pages                    9996 non-null   str
 30  Keyword_Difficulty                   9996 non-null   float64
 31  CPC_for_Paid_Keywords ($)            9996 non-null   float64
 32  Indexed_Pages                        9996 non-null   int64
 33  Mobile_vs_Desktop_Traffic_Split (%)  9996 non-null   float64
 34  Organic_Revenue ($)                  9996 non-null   float64
 35  Page_Load_Time (sec)                 9996 non-null   float64
 36  Core_Web_Vitals_LCP (sec)            9996 non-null   float64
 37  Core_Web_Vitals_FID (ms)             9996 non-null   float64
 38  Core_Web_Vitals_CLS                  9996 non-null   float64
 39  Social_Shares                        9996 non-null   int64
 40  Referral_Traffic                     9996 non-null   int64
 41  Technical_SEO_Errors                 9996 non-null   int64
 42  Bounce_Rate_by_Device_Mobile (%)     9996 non-null   float64
 43  Time_to_First_Byte_TTFB (ms)         9996 non-null   int64
dtypes: datetime64[us](1), float64(18), int64(14), str(11)
memory usage: 3.4 MB

In [4]:
df.isnull().sum()

Date                                   0
Month                                  0
Year                                   0
Quarter                                0
Time Of Day                            0
Primary Keywords                       0
Secondary Keywords                     0
Long-Tail Keywords                     0
Location                               0
Social Media Source                    0
Media Type                             0
Device Type                            0
Organic_Traffic                        0
Keywords_Ranking                       0
Clicks                                 0
Impressions                            0
CTR (%)                                0
Average_Position                       0
Backlinks                              0
Domain_Authority                       0
Bounce_Rate (%)                        0
Pages_per_Session                      0
Organic_vs_Paid_Traffic_Split (%)      0
Organic_Traffic_Growth_Rate (%)        0
Conversion_Rate (%)                    0
Goal_Completions                       0
Average_Session_Duration (sec)         0
New_vs_Returning_Visitors (%)          0
Exit_Rate (%)                          0
Top_Landing_Pages                      0
Keyword_Difficulty                     0
CPC_for_Paid_Keywords ($)              0
Indexed_Pages                          0
Mobile_vs_Desktop_Traffic_Split (%)    0
Organic_Revenue ($)                    0
Page_Load_Time (sec)                   0
Core_Web_Vitals_LCP (sec)              0
Core_Web_Vitals_FID (ms)               0
Core_Web_Vitals_CLS                    0
Social_Shares                          0
Referral_Traffic                       0
Technical_SEO_Errors                   0
Bounce_Rate_by_Device_Mobile (%)       0
Time_to_First_Byte_TTFB (ms)           0
dtype: int64

## Identifikasi Kolom yang Akan Dipakai

In [5]:
seo_df = df[
    [
        "Date",
        "Primary Keywords",
        "Location",
        "Device Type",
        "Organic_Traffic",
        "Keywords_Ranking",
        "Clicks",
        "Impressions",
        "CTR (%)",
        "Average_Position",
        "Conversion_Rate (%)",
        "Top_Landing_Pages",
        "Keyword_Difficulty",
        "Organic_Revenue ($)",
        "Technical_SEO_Errors"
    ]
]

seo_df.head()

,Date,Primary Keywords,Location,Device Type,Organic_Traffic,Keywords_Ranking,Clicks,Impressions,CTR (%),Average_Position,Conversion_Rate (%),Top_Landing_Pages,Keyword_Difficulty,Organic_Revenue ($),Technical_SEO_Errors
0,2023-01-01 00:00:00,eco-friendly accessories,Mexico,Mobile,7965,81,2139,43080,3.14,46.44,6.80,Category Page,65.48,3597.90,13
1,2023-01-01 01:00:00,eco-friendly accessories,Mexico,Laptop,6553,45,2799,15013,1.43,31.60,3.50,Homepage,43.29,5806.19,19
2,2023-01-01 02:00:00,vegan leather handbags,Australia,Laptop,1982,96,2990,28455,3.45,36.20,12.36,Homepage,79.87,1170.33,7
3,2023-01-01 03:00:00,organic cotton apparel,Mexico,Desktop,6363,78,2905,3189,0.96,30.98,3.98,Blog Post,56.45,1182.17,7
4,2023-01-01 04:00:00,organic cotton apparel,Germany,Laptop,8720,79,337,27380,8.30,9.93,7.88,Homepage,54.30,692.14,14

## Buat Opportunity Score

In [6]:
seo_df["Opportunity_Score"] = (
    seo_df["Impressions"] *
    (1 / seo_df["Average_Position"])
)

In [7]:
seo_df[
    [
        "Primary Keywords",
        "Impressions",
        "Average_Position",
        "Opportunity_Score"
    ]
].head()

           Primary Keywords  Impressions  Average_Position  Opportunity_Score
0  eco-friendly accessories        43080             46.44         927.648579
1  eco-friendly accessories        15013             31.60         475.094937
2    vegan leather handbags        28455             36.20         786.049724
3    organic cotton apparel         3189             30.98         102.937379
4    organic cotton apparel        27380              9.93        2757.301108

In [8]:
## Buat Action Category

In [9]:
def classify_position(position):

    if position <= 3:
        return "Maintain"

    elif position <= 10:
        return "Quick Win"

    elif position <= 20:
        return "Growth Opportunity"

    else:
        return "Low Priority"

In [10]:
seo_df["Action_Category"] = seo_df[
    "Average_Position"
].apply(classify_position)

In [11]:
seo_df[
    [
        "Primary Keywords",
        "Average_Position",
        "Action_Category"
    ]
].head()

           Primary Keywords  Average_Position Action_Category
0  eco-friendly accessories             46.44    Low Priority
1  eco-friendly accessories             31.60    Low Priority
2    vegan leather handbags             36.20    Low Priority
3    organic cotton apparel             30.98    Low Priority
4    organic cotton apparel              9.93       Quick Win

In [12]:
seo_df["Action_Category"].value_counts()

Action_Category
Low Priority          6026
Growth Opportunity    2036
Quick Win             1513
Maintain               421
Name: count, dtype: int64

In [15]:
seo_df.to_csv(
    "../data_clean/seo_dashboard_final.csv",
    index=False
)

print("Export berhasil")

Export berhasil

## pahami cerita datanya dulu

In [19]:
seo_df.groupby("Action_Category").agg({
    "Clicks": "sum",
    "Impressions": "sum",
    "Organic_Traffic": "sum",
    "Organic_Revenue ($)": "sum"
}).round(2)

                     Clicks  Impressions  Organic_Traffic  Organic_Revenue ($)
Action_Category
Growth Opportunity  3162777     51046439         10153937          10365840.05
Low Priority        9239736    154232674         30659556          30371749.26
Maintain             629193     10511076          2094992           2110804.52
Quick Win           2279546     39014307          7523674           7520081.45

In [20]:
top_opportunity = (
    seo_df
    .sort_values(by="Opportunity_Score", ascending=False)
)

top_opportunity[
    [
        "Primary Keywords",
        "Impressions",
        "Average_Position",
        "Opportunity_Score",
        "Action_Category"
    ]
].head(20)

,Primary Keywords,Impressions,Average_Position,Opportunity_Score,Action_Category
3862,sustainable outdoor gear,45325,1.04,43581.730769,Maintain
802,organic cotton apparel,43918,1.03,42638.834951,Maintain
2335,eco-friendly accessories,46766,1.10,42514.545455,Maintain
4266,sustainable outdoor gear,43818,1.07,40951.401869,Maintain
2690,eco-friendly clothing,46935,1.15,40813.043478,Maintain
8926,eco-friendly clothing,49547,1.27,39013.385827,Maintain
4134,recycled fabric dresses,43066,1.11,38798.198198,Maintain
3122,organic cotton apparel,44368,1.17,37921.367521,Maintain
9812,recycled fabric dresses,48342,1.30,37186.153846,Maintain
1575,recycled fabric dresses,49436,1.33,37169.924812,Maintain
3338,vegan leather handbags,44346,1.20,36955.000000,Maintain
8869,eco-friendly accessories,41552,1.16,35820.689655,Maintain
5569,vegan leather handbags,49072,1.37,35818.978102,Maintain
7917,eco-friendly accessories,35926,1.02,35221.568627,Maintain
6815,sustainable outdoor gear,36605,1.05,34861.904762,Maintain
1988,eco-friendly accessories,37661,1.11,33928.828829,Maintain
5321,sustainable outdoor gear,34943,1.03,33925.242718,Maintain
8239,vegan leather handbags,42203,1.27,33230.708661,Maintain
7984,sustainable outdoor gear,40743,1.24,32857.258065,Maintain
8884,vegan leather handbags,43555,1.33,32748.120301,Maintain

In [21]:
seo_df["Opportunity_Score_v2"] = (
    seo_df["Impressions"]
    *
    seo_df["Average_Position"]
)

In [22]:
quick_win = seo_df[
    (seo_df["Average_Position"] >= 4)
    &
    (seo_df["Average_Position"] <= 15)
]

In [23]:
quick_win = quick_win.sort_values(
    by="Impressions",
    ascending=False
)

In [24]:
quick_win[
    [
        "Primary Keywords",
        "Impressions",
        "Average_Position",
        "Action_Category"
    ]
].head(20)

,Primary Keywords,Impressions,Average_Position,Action_Category
8163,eco-friendly clothing,49999,14.32,Growth Opportunity
705,eco-friendly clothing,49984,10.47,Growth Opportunity
3014,eco-friendly accessories,49980,9.91,Quick Win
8649,sustainable outdoor gear,49961,13.60,Growth Opportunity
3259,vegan leather handbags,49948,6.84,Quick Win
7077,eco-friendly accessories,49945,7.83,Quick Win
3306,eco-friendly accessories,49942,5.69,Quick Win
1869,eco-friendly clothing,49912,14.83,Growth Opportunity
8271,eco-friendly clothing,49900,7.35,Quick Win
3135,eco-friendly clothing,49890,11.39,Growth Opportunity
5629,organic cotton apparel,49889,10.86,Growth Opportunity
8971,vegan leather handbags,49883,7.49,Quick Win
35,eco-friendly accessories,49869,6.44,Quick Win
8929,recycled fabric dresses,49786,4.99,Quick Win
3675,vegan leather handbags,49781,8.61,Quick Win
2772,eco-friendly accessories,49774,13.79,Growth Opportunity
9221,eco-friendly accessories,49762,6.10,Quick Win
2978,organic cotton apparel,49733,14.12,Growth Opportunity
7187,recycled fabric dresses,49661,7.44,Quick Win
5187,eco-friendly clothing,49647,11.06,Growth Opportunity

## distribusi kategori

In [25]:
seo_df.groupby("Action_Category").agg({
    "Clicks":"sum",
    "Impressions":"sum",
    "Organic_Traffic":"sum",
    "Organic_Revenue ($)":"sum"
}).round(2)

                     Clicks  Impressions  Organic_Traffic  Organic_Revenue ($)
Action_Category
Growth Opportunity  3162777     51046439         10153937          10365840.05
Low Priority        9239736    154232674         30659556          30371749.26
Maintain             629193     10511076          2094992           2110804.52
Quick Win           2279546     39014307          7523674           7520081.45